### ISSUE TITLE
SteadyDB.py", line 605   ,   TypeError: expecting a dictionary, sequence or keyword args

### ISSUE THREAD

**Issue by guorouda** [MaiXiaochai/OraclePool#1]
尝试有来查询一下数据，发现这个错误，完全没有头绪。请指点一下。
python 3.6

`/home/ron/git/OraclePool/venv/bin/python /home/ron/git/OraclePool/oracle_pool.py
Traceback (most recent call last):
  
File "/home/ron/git/OraclePool/oracle_pool.py", line 172, in <module>
    demo()
  
File "/home/ron/git/OraclePool/oracle_pool.py", line 167, in demo
    result = orcl.fetch_all(sql)
  
File "/home/ron/git/OraclePool/oracle_pool.py", line 117, in fetch_all
    conn, cursor = self.__execute(sql, args)
  
File "/home/ron/git/OraclePool/oracle_pool.py", line 106, in __execute
    cursor.execute(sql, args)
  
File "/home/ron/git/OraclePool/venv/lib/python3.6/site-packages/DBUtils/SteadyDB.py", line 605, in tough_method
    result = method(*args, **kwargs)  # try to execute
TypeError: expecting a dictionary, sequence or keyword args`

**Comment by guorouda** [comment]
oracle_pool.py 第106句 改为 cursor.execute(sql) 代码就能够执行了。保留 args 的写法请 博主 给个修改办法。 水平有限，请指正。
